"es":
  "es_url" : ""
  "activity_index" : "" 
  "empi_index" : ""
  "attribution_index" : ""


"azkaban" :
  "az_url" : ""
  "username" : ""
  "password" : ""


"merge-api" : 
  "api_base_url" : ""
  "auth_base_url" : ""
  "username" : ""
  "password" : ""

